### ISSUE TITLE
Bundle Resource 'GoogleMaps.bundle/blabla' not found on disk

### ISSUE THREAD

**Issue by themronion** [AdamEssenmacher/GoogleApisForiOSComponents#50]
### Steps to reproduce
1. Create plain .net ios project
2. Add `<PackageReference Include="AdamE.Google.iOS.Maps" Version="9.1.1.1" />`
3. Observe 99+ errors

**Comment by Digifais** [comment]
@themronion That's weird, since I'm consuming 9.1.1 in my own app and that's working perfectly fine. This also has been tested by @AdamEssenmacher in the sample app of the https://github.com/amay077/Xamarin.Forms.GoogleMaps repo as far as I know.

**Comment by themronion** [comment]
I wonder what other bindings might be affected after this one: https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/pull/49

**Comment by Digifais** [comment]
@themronion Can you post the complete list of errors that you get though? Since 99+ seems to be a bit much.

I get 4 errors with `9.1.1.1` (same kind as you `Bundle Resource X not found on disk`), which seem to be expected looking at the binding for GoogleMaps 9.1.1 and looking at the Maps for iOS SDK repository from Google as well. Not entirely sure why the binding was working with Xamarin.Build.Download 0.11.0 before since that seemed to pull in resources that were removed in the GoogleMaps 9.1.1 version, Xamarin.Build.Download 0.11.4 seems to be pulling in the correct ones only.

**Comment by themronion** [comment]
@Digifais yeah, I've cleaned the XamarinBuildDownload/GMps-9.1.1 folder and now have 4 as well

**Comment by Digifais** [comment]
@themronion I'll create a PR to fix the GoogleMaps binding later today, I'll go through the resources one by one again and see what is missing and should be removed.

@AdamEssenmacher, we should check the other existing bindings as well to see if they have the same problem with Xamarin.Build.Download 0.11.4

**Comment by Digifais** [comment]
@themronion This was only an issue with the Google Maps binding, before I became a contributor, I was working on a fork of my own. Somewhere along the line, me and @AdamEssenmacher made a mistake by merging the source repo back into my fork and that's where some changes for the 9.1.1 binding were removed. See https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/commit/07c4ebd4668d460421da901e28f677ca49e7afa0#diff-fade105c9a83b8be1f9f162c500eaaa9d8715d707829a0bd447197dfc097faa6 for reference.

**Comment by AdamEssenmacher** [comment]
Yep. Merge fail on my part. Doesn't seem like an XBD problem at all, and it only affected GoogleMaps. 9.1.1.2 should be available on NuGet now.
